import React, { useState } from 'react';
import { MeetingAnalysis, ActionItem } from '../types';
import { CheckCircleIcon, CopyIcon, NotionIcon, SlackIcon } from './Icons';

interface ResultsViewProps {
  data: MeetingAnalysis;
  onReset: () => void;
}

const ResultsView: React.FC<ResultsViewProps> = ({ data, onReset }) => {
  const [activeTab, setActiveTab] = useState<'summary' | 'transcript'>('summary');
  const [copied, setCopied] = useState<string | null>(null);

  const copyToClipboard = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    setCopied(type);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleExport = (platform: string) => {
    alert(`Export to ${platform} clicked! \n\nIn a production app, this would trigger an OAuth flow to create a page/message in ${platform}.`);
  };

  const formattedActionItems = data.action_items.map(i => 
    `- [ ] ${i.description} (Owner: ${i.owner}, Due: ${i.due_date || 'TBD'})`
  ).join('\n');

  const formattedSummary = `
# Meeting Summary
${data.summary_points.map(p => `• ${p}`).join('\n')}

## Decisions
${data.decisions.map(d => `• ${d}`).join('\n')}

## Action Items
${formattedActionItems}
  `.trim();

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      {/* Header / Actions */}
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
        <div>
           <button onClick={onReset} className="text-sm text-slate-500 hover:text-indigo-600 mb-1 font-medium">
             ← Upload another meeting
           </button>
           <h1 className="text-3xl font-bold text-slate-900">Meeting Notes</h1>
           <p className="text-slate-500 text-sm">Generated by AI • {new Date().toLocaleDateString()}</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={() => handleExport('Notion')}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors shadow-sm font-medium text-sm"
          >
            <NotionIcon className="w-4 h-4" /> Notion
          </button>
          <button 
             onClick={() => handleExport('Slack')}
             className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors shadow-sm font-medium text-sm"
          >
            <SlackIcon className="w-4 h-4" /> Slack
          </button>
          <button 
             onClick={() => copyToClipboard(formattedSummary, 'all')}
             className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-md font-medium text-sm"
          >
            {copied === 'all' ? <CheckCircleIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
            {copied === 'all' ? 'Copied!' : 'Copy All'}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Summary & Actions (8 cols) */}
        <div className="lg:col-span-8 space-y-8">
            
            {/* Tabs (Mobile Only mainly, but functional) */}
            <div className="flex border-b border-slate-200 lg:hidden">
                <button 
                    onClick={() => setActiveTab('summary')}
                    className={`px-4 py-2 font-medium text-sm ${activeTab === 'summary' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-slate-500'}`}
                >
                    Summary & Actions
                </button>
                <button 
                    onClick={() => setActiveTab('transcript')}
                    className={`px-4 py-2 font-medium text-sm ${activeTab === 'transcript' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-slate-500'}`}
                >
                    Transcript
                </button>
            </div>

            {/* Content Container */}
            <div className={`${activeTab === 'summary' ? 'block' : 'hidden lg:block'}`}>
                
                {/* Executive Summary */}
                <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                    <div className="p-6 border-b border-slate-50 bg-slate-50/50 flex justify-between items-center">
                        <h2 className="text-lg font-bold text-slate-800">Key Points</h2>
                         <button 
                             onClick={() => copyToClipboard(data.summary_points.join('\n'), 'summary')}
                             className="text-xs font-medium text-indigo-600 hover:text-indigo-800 flex items-center gap-1"
                         >
                            {copied === 'summary' ? 'Copied' : 'Copy'}
                         </button>
                    </div>
                    <div className="p-6">
                        <ul className="space-y-3">
                            {data.summary_points.map((point, i) => (
                                <li key={i} className="flex items-start gap-3 text-slate-700 leading-relaxed">
                                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-400 flex-shrink-0"></span>
                                    {point}
                                </li>
                            ))}
                        </ul>
                    </div>
                </section>

                {/* Decisions */}
                <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden mt-6">
                     <div className="p-6 border-b border-slate-50 bg-slate-50/50">
                        <h2 className="text-lg font-bold text-slate-800">Decisions Made</h2>
                    </div>
                    <div className="p-6">
                        {data.decisions.length > 0 ? (
                            <ul className="space-y-3">
                                {data.decisions.map((decision, i) => (
                                    <li key={i} className="flex items-start gap-3 text-slate-700 leading-relaxed">
                                        <CheckCircleIcon className="w-5 h-5 text-emerald-500 mt-0.5 flex-shrink-0" />
                                        {decision}
                                    </li>
                                ))}
                            </ul>
                        ) : (
                            <p className="text-slate-500 italic">No explicit decisions detected.</p>
                        )}
                    </div>
                </section>

                {/* Action Items */}
                <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden mt-6">
                    <div className="p-6 border-b border-slate-50 bg-slate-50/50 flex justify-between items-center">
                        <h2 className="text-lg font-bold text-slate-800">Action Items</h2>
                         <button 
                             onClick={() => copyToClipboard(formattedActionItems, 'actions')}
                             className="text-xs font-medium text-indigo-600 hover:text-indigo-800 flex items-center gap-1"
                         >
                             {copied === 'actions' ? 'Copied' : 'Copy'}
                         </button>
                    </div>
                    <div className="p-0">
                        {data.action_items.length > 0 ? (
                            <div className="divide-y divide-slate-100">
                                {data.action_items.map((item, i) => (
                                    <div key={i} className="p-6 flex flex-col md:flex-row md:items-start gap-4 hover:bg-slate-50 transition-colors">
                                        <div className="flex-1">
                                            <p className="text-slate-800 font-medium">{item.description}</p>
                                        </div>
                                        <div className="flex gap-4 md:w-64 flex-shrink-0">
                                            <div className="flex-1">
                                                <span className="block text-xs text-slate-400 uppercase tracking-wider font-semibold mb-1">Owner</span>
                                                <div className="flex items-center gap-2">
                                                     <div className="w-6 h-6 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center text-xs font-bold">
                                                        {item.owner.charAt(0).toUpperCase()}
                                                     </div>
                                                     <span className="text-sm text-slate-700">{item.owner}</span>
                                                </div>
                                            </div>
                                            <div className="flex-1">
                                                <span className="block text-xs text-slate-400 uppercase tracking-wider font-semibold mb-1">Due</span>
                                                <span className={`text-sm font-medium ${!item.due_date || item.due_date === 'TBD' ? 'text-slate-400' : 'text-slate-700'}`}>
                                                    {item.due_date || 'TBD'}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        ) : (
                             <div className="p-6">
                                <p className="text-slate-500 italic">No action items detected.</p>
                             </div>
                        )}
                    </div>
                </section>
            </div>
        </div>

        {/* Right Column: Transcript (4 cols) - Sticky on Desktop */}
        <div className={`lg:col-span-4 ${activeTab === 'transcript' ? 'block' : 'hidden lg:block'}`}>
            <div className="lg:sticky lg:top-8 max-h-[calc(100vh-4rem)] flex flex-col bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                <div className="p-4 border-b border-slate-50 bg-slate-50/50 flex justify-between items-center flex-shrink-0">
                    <h2 className="text-lg font-bold text-slate-800">Transcript</h2>
                     <button 
                         onClick={() => copyToClipboard(data.transcript, 'transcript')}
                         className="text-xs font-medium text-slate-500 hover:text-indigo-600"
                     >
                         {copied === 'transcript' ? 'Copied' : 'Copy Text'}
                     </button>
                </div>
                <div className="p-4 overflow-y-auto flex-grow custom-scrollbar">
                    <p className="text-sm text-slate-600 leading-relaxed whitespace-pre-wrap font-mono">
                        {data.transcript}
                    </p>
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};

export default ResultsView;
